version: 2.1

executors:
  node_14:
    docker:
      - image: circleci/node:14
    working_directory: ~/app

  node_16:
    docker:
      - image: circleci/node:16
    working_directory: ~/app

commands:
  install_dependencies:
    steps:
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-v1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

  run_test:
    steps:
      - checkout
      - install_dependencies
      - run: yarn audit --groups dependencies
      - run: yarn run ts-test
      - run: yarn run lint

  # node14 doesn't work
  run_test_with_ruby:
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt install -yq ruby-full
          sudo gem install textlint-ruby
      - run: yarn run test

jobs:
  node_14:
    executor: node_14
    steps:
      - run_test

  node_16:
    executor: node_16
    steps:
      - run_test
      - run_test_with_ruby

  deploy:
    executor: node_16
    steps:
      - checkout
      - install_dependencies
      - run: yarn run build
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - run: npm publish

workflows:
  version: 2

  test:
    jobs:
      - node_14
      - node_16
      - deploy:
          requires:
            - node_14
            - node_16
          filters:
            tags:
              only: /^v.*/
            branches:
              only: []
